version: "3"
services:
    yas:
        image: "yas:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: yas
        stdin_open: true
        tty: true
        working_dir: '/yas-dev'
        volumes:
            - ".:/yas-dev"
